Repository LemonKaiser/WH14K, pull requests merged in 2025-09, with the labels that each got.

#14 Fix&Localisation Grenades
  Resources/Locale/ru-RU/_wh40k/prototypes/Weapons/Throwable/grenades.ftl
  Resources/Prototypes/_WH40K/Entities/Objects/Weapons/Throwable/grenades.yml
Labels: S: Untriaged, S: Needs Review, Changes: No C#, size/S

#20 2
  Resources/Prototypes/Datasets/Names/borg.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Head/hardsuit-helmet.yml
  Resources/Prototypes/_WH40K/Entities/Objects/Weapons/Guns/Bolters/bolters.yml
  Resources/Prototypes/_WH40K/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
  Resources/Prototypes/_WH40K/Roles/Jobs/departments.yml
Labels: size/M, S: Needs Review, Changes: No C#

#23 fix
  Resources/Prototypes/_WH40K/Entities/Clothing/Back/backpacksguard.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Belt/guardbelts.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Eyes/guardhud.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Head/flackhelm.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Neck/cloath.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Neck/robes.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/OuterClothing/armor.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/OuterClothing/comissartrench.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/OuterClothing/flack.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/OuterClothing/flackgen.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Shoes/boots.yml
  Resources/Prototypes/_WH40K/Entities/Clothing/Uniform/jumpsuits.yml
  Resources/Prototypes/_WH40K/Entities/Objects/Weapons/Guns/battery_guns.yml
  Resources/Textures/_WH40K/Objects/Weapons/Guns/Stubrevolver/heavystubrevolver.rsi/bolt-open.png
  Resources/Textures/_WH40K/Objects/Weapons/Guns/Stubrevolver/heavystubrevolver.rsi/meta.json
  Resources/Textures/_WH40K/Objects/Weapons/Guns/Stubrevolver/stubrevolver.rsi/bolt-open.png
  Resources/Textures/_WH40K/Objects/Weapons/Guns/Stubrevolver/stubrevolver.rsi/meta.json
Labels: size/M, S: Untriaged, S: Needs Review, Changes: Sprites, Changes: No C#
